# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 3/5 * * 




jobs:
  job_id_test:
     name: job_id_test
     runs-on: [ubuntu-latest]
     steps: 
       - name: cpu_info
         run: cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l
       - name: free_info
         run: echo free -h
       - name: df_info
         run: echo df -h
