# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 122.51.85.74
        username: root
        password: '#sky132@'
        port: 22
        script: |
          # !/bin/bash
          source /etc/profile
          export JAVA_HOME=/usr/local/jdk1.8.0_201
          echo "javabin"
          export JAVA_BIN=$JAVA_HOM/bin
          echo "javalib"
          export JAVA_LIB=$JAVA_HOME/lib
          echo "classpath"
          export CLASSPATH=.:$JAVA_LIB/tools.jar:$JAVA_LIB/dt.jar
          echo "path"
          export PATH=$JAVA_BIN:$PATH
          echo "git"
          export PATH=$PATH:/usr/local/git/bin
          echo "maven"
          export M2_HOME=/usr/local/caoxc/apache-maven-3.3.9/
          #export PATH=$PATH:$JAVA_HOME/bin:$M2_HOME/bin
          echo "path"
          export PATH=${M2_HOME}/bin:${PATH}
          date=`date +%Y%m%d%H%M%S`
          RUN_PATH=/usr/local/caoxc/
          CODE_PATH=/usr/local/caoxc/code/
          APP_NAME=springboot.jar
          JAR_PATH=/usr/local/caoxc/code/action_test/springboot/target/
          rm -rf /usr/local/caoxc/code/action_test
          cd ${CODE_PATH}
          git clone  https://github.com/CiaoBean/action_test.git
          cd ${CODE_PATH}/action_test
          mvn clean install -Dmaven.test.skip=true
          cd ${JAR_PATH}
          PID=$(ps -ef | grep springboot-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{ print $2 }')
          if [ -z "$PID" ]
          then
              echo Application is already stopped
          else
              echo kill $PID
              kill -9 $PID
          fi
          echo "运行jar"
          exit
         ## nohup java -jar springboot-0.0.1-SNAPSHOT.jar &
         
