# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_id_test:
     name: job_id_test
     runs-on: [ubuntu-latest]
     steps: 
       - name: test
         run: echo hello
  maven_job:
    name: maven_job
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
              java-version: 1.8
      - name: Build with Maven 
        run: mvn -B package --file pom.xml
  deploy_job: 
    needs: [maven_job]
    name: deploy_job
    runs-on: [ubuntu-latest]
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          # SMTP server address
          server_address: smtp.exmail.qq.com
          # SMTP server port
          server_port: 465
          # Authenticate as this user to SMTP server
          username: caoxc@entrobus.com
          # Authenticate with this password to SMTP server
          password: Cxc19940305
          # Subject of mail message
          subject: finish deploy
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: finish deploy successfully
          # Recipients mail addresses (separated with comma)
          to: 190207920@qq.com
          # Full name of mail sender (might be with an email address specified in <>)
          from: caoxc@entrobus.com
          # Content-Type HTTP header (text/html or text/plain)
          content_type: finish deploy successfully
