# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_id_test:
     name: job_id_test
     runs-on: [ubuntu-latest]
     steps: 
       - name: test
         run: echo hello
  maven_job:
    name: maven_job
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
              java-version: 1.8
      - name: Build with Maven 
        run: mvn -B package --file pom.xml
      - name: pwd 
        run: pwd
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 122.51.85.74
          username: root
          password: '#sky132@'
          port: 22
          source: "/home/runner/work/action_test/action_test/springboot/target/springboot-0.0.1-SNAPSHOT.jar"
          target: "/usr/local/caoxc/"
